# 3. Решение частичной проблемы собственных значений

In [1]:
import numpy as np

In [2]:
A = [
    [-1.53698, -0.19907, 0.95855],
    [-0.19907, 1.17742, 0.06992],
    [0.95855, 0.06992, -1.55151]
]

n = len(A)

eps = 0.0001

для проверки получим собственные числа и векторы через numpy

In [3]:
spectre = np.linalg.eigvals(np.matrix(A))
spectral_radix = max(spectre, key=abs)
eigvecs = np.linalg.eig(np.matrix(A))[1]
spectre, spectral_radix, eigvecs

(array([-2.51260262, -0.59040918,  1.1919418 ]),
 -2.512602623442085,
 matrix([[-7.05231401e-01, -7.05234216e-01, -7.27555552e-02],
         [-5.14445157e-02, -5.14473772e-02,  9.97349803e-01],
         [ 7.07108289e-01, -7.07105273e-01, -1.87326809e-06]]))

## Степенной метод

In [4]:
maxeig = [0] * n
prev_maxeig = [100] * n
y = [1] * n
cnt = 0
while max([abs(maxeig[i] - prev_maxeig[i]) for i in range(n)]) > eps:
    cnt += 1
    prev_y, prev_maxeig = y, maxeig
    y = np.matmul(A, y)
    maxeig = [y[i] / prev_y[i] for i in range(n)]

число итераций:

In [5]:
cnt

25

максимальное по модулю собственное число:

In [6]:
maxeigvalue = maxeig[0]
maxeigvalue

-2.5126027437159197

соответствующий ему собственный вектор:

In [7]:
maxeigvec = y / np.linalg.norm(y)
maxeigvec

array([-0.70523141, -0.05144437,  0.70710829])

еще проверка:

In [8]:
a = [maxeigvalue * x for x in maxeigvec]
b = np.matmul(A, maxeigvec)
a, b

([1.7719663815710365, 0.12925925708913777, -1.776682226726991],
 array([ 1.77196626,  0.1292598 , -1.77668214]))

## Метод скалярных произведений:

In [9]:
y = [1] * n
maxeig = 0
prev_maxeig = 100
cnt = 0
while abs(maxeig - prev_maxeig) > eps:
    cnt += 1
    prev_y, prev_maxeig = y, maxeig
    y = np.matmul(A, y)
    maxeig = np.inner(prev_y, y) / np.inner(prev_y, prev_y)

максимальное по модулю собственное число:

In [10]:
maxeig

-2.512580877088742

In [11]:
a = [maxeigvalue * x for x in maxeigvec]
b = np.matmul(A, maxeigvec)
a, b

([1.7719663815710365, 0.12925925708913777, -1.776682226726991],
 array([ 1.77196626,  0.1292598 , -1.77668214]))

число итераций:

In [12]:
cnt

13

собственный вектор аналогично

In [13]:
maxeigvec = y / np.linalg.norm(y)
maxeigvec

array([-0.7053147 , -0.05029817,  0.70710768])